### PR TITLE
Tc/id string callback customizations/at 3287

### PR DESCRIPTION
**Pull request by kidatsy**
Modifies PayPal's [SkipTo](https://github.com/paypal/skipto) library to include the following functionalities:
- ability to specify in the config for ids:
    - custom `description` string for display in the list item link
    - custom callback to be called on clicking the link for each item
- additional booleans for:
    - focusing on the item, rather than follow the `#[ID]` link on click, by default in the absence of a callback
    - including a `#` in the app route on launching the menu or not
    - enumerating each element in the list, rather than displaying the HTML element type
    - all of the above are defaulted to existing behavior of the root repo, to replicate existing default behavior
- adds ability to `init` with a directly passed-in `customConfig` object, rather than relying on a global object to be defined elsewhere
- since some of the functionality above requires changes to `dropMenu.js` as well, extends initiation of that object to include a `config` object as well, carrying the callbacks that `skipTo.js` was initiated with.
    - callbacks currently only apply to `id` elements, as it fits our current specs, need to spend some time looking at opening the config options above to all element types for general use.

I'm planning to submit a PR for merging back into the original repo, once we've got this fully implemented on the platform and our custom changes settled.

### CODE REVIEW

**Comment by kidatsy** [comment]
Here's an example of the config, some version of which I'm planning to run for the platform:

```
    config: {
        main:      '',
        landmarks: '',
        sections:  '',
        headings:  '',
        ids:       [
            {
                id: 'sidebar',
                callback: function () {
                    console.log('doing the sidebar callback!');
                }
            },
            {
                id: 'conversations',
                description: 'Conversations',
                callback: function () {
                    console.log('doing the conversations callback!');
                }
            }
        ],
        accessKey: '0',
        wrap: "true",
        focusOnClick: "true",
        hashOnMenu: "false",
        enumerateElements: "true",
    },
```

**Comment by shaynemartin91** [comment]
Have you talked to the skipto maintainers about our needs/these changes, is this the way they suggested going about it? I'm just hesitant to add a dependency that we have to maintain in the event that their team decides they don't want this functionality. It feels like we're potentially painting ourselves into a corner.

Also, will this library work with react as convert more and more of the platform? A fully reactified app doesn't typically have static IDs except at the very top-most level, but I haven't looked at this library enough to know how that would work here.

**Comment by kidatsy** [comment]
Thanks for the note, @shaynemartin91, will check with them on that.

Re React: I know it doesn't normally work with IDs, so one of my action items in the write-up I did here: https://admin.crisistextline.org/confluence/pages/viewpage.action?spaceKey=PD&title=Implementing+SkipTo+for+accessible+jump+menus is to insert IDs where appropriate. In the screenshot I posted there, the #conversations ID is one I inserted into the conversations portal div, and it worked with the library great. I'm imagining there only being a max of ~6-8 items in the list, most of them a this higher level, so I think it would fit in with React's overall preference for classes.

I did a cursory search for Reactified versions of something like this, but didn't come up with any options that had the same kind of functionality, and of course there's the issue of needing to bridge both the React and legacy js elements.

**Comment by kidatsy** [comment]
Questions left for maintainers here: https://github.com/paypal/skipto/issues/43

**Comment by kidatsy** [comment]
This has been merged into the master branch of the original repo, so this PR is no longer necessary. Will be pulling from there to generate the files now

**Pull request closed without merging**
